title: This is a Podcast
#author: B+MC
email: 
description: "This is a Podcast is a podcast."
baseurl: "/thisisapodcast"
url: "http://ghostdreamz.github.io/thisisapodcast"
# social links
twitter_username: chowthedog
github_username:  ghostdreamz
#rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

#show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
#theme: minima
#exclude:
#  - Gemfile
#  - Gemfile.lock
